name: delta_markdown
version: 0.0.1

description: A library for converting between Delta and Markdown.
author: Till Friebe, Kolja Esders, Dart Team <misc@dartlang.org
homepage: https://github.com/friebetill/notus_markdown

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  args: ^1.0.0
  charcode: ^1.1.0
  flutter_quill: 0.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.0.0
  build_version: ^2.0.0
  collection: ^1.2.0
  expected_output: ^1.2.1
  path: ^1.3.1
  pedantic: ^1.3.0
  test: ^1.2.0
  yaml: ^2.1.8
