name: delta_markdown
version: 0.0.2

description: A library for converting between Delta and Markdown.
homepage: https://github.com/friebetill/notus_markdown

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  charcode: ^1.1.0
  flutter_quill: ^0.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.3.0
  test: ^1.2.0
