name: notus_markdown
version: 0.0.1

description: A library for converting between Notus and Markdown.
author: Kolja Esders, Dart Team <misc@dartlang.org
homepage: https://github.com/kolja-esders/notus_markdown

executables:
  markdown:

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  args: ^1.0.0
  charcode: ^1.1.0
  quill_delta: any
  notus:
    git:
      url: git@github.com:kolja-esders/zefyr.git
      ref: flutter-master
      path: packages/notus

dev_dependencies:
  build_runner: ^1.0.0
  build_version: ^2.0.0
  build_web_compilers: ^1.0.0
  collection: ^1.2.0
  expected_output: ^1.2.1
  html: '>=0.12.2 <0.14.0'
  js: ^0.6.1
  path: ^1.3.1
  pedantic: ^1.3.0
  test: ^1.2.0
  yaml: ^2.1.8
